# Generated by Django 4.2 on 2024-02-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
    ]
