# Generated by Django 5.0.2 on 2025-08-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slide_1', models.ImageField(upload_to='media/')),
                ('slide_2', models.ImageField(upload_to='media/')),
                ('slide_3', models.ImageField(upload_to='media/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
